# Auto-generated by /home/piegon01/src/uefi/edk2-platforms/edk2/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/piegon01/src/uefi/edk2-platforms
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/piegon01/src/uefi/edk2-platforms/edk2/BaseTools
fi
if [ -e /home/piegon01/src/uefi/edk2-platforms/edk2/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/piegon01/src/uefi/edk2-platforms/edk2/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/piegon01/src/uefi/edk2-platforms/edk2/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
